#Transpiled With The JavaSkript Project

on load:
    send "[PenguinProtocol] Skript Loaded Successfully! (v1.0)" to console
    broadcast "[PenguinProtocol] Loaded!"

on join:
    set join message to "Welcome, %player%!"
    wait 0.5 seconds
    send "Current Time: %time%" to player

on quit:
    set quit message to "Bye, %player%!"

on damage:
    victim is a player
    attacker's held item is chest
    send "[PenguinProtocol] Looking In %victim%'s Inventory..." to attacker
    send "[PenguinProtocol] Operator %attacker% Is Looking Through Your Inventory!" to victim
    send "[PenguinProtocol] Operator %attacker% Is Searching Through %victim%'s Inventory.'" to console

every 1 real hours:
    broadcast "[PenguinProtocol] Creating Backup... (This May Be Laggy!)"
    broadcast "[PenguinProtocol] Backup Complete! (Next In One Hour)"

